### ISSUE TITLE
Support for authorization methods.

### ISSUE THREAD

**Issue by vnermolaev** [influxdata/rskafka#125]
Hi there,

I am attempting to use `rskafka` to connect to a Kafka cluster using authorization using this [tutorial](https://medium.com/swlh/a-free-apache-kafka-cloud-service-and-how-to-quickly-get-started-with-it-8f14520fff35) (for NodeJS).
Is authz supported at all? If so how do I provide such data to `ClientBuilder`? I cannot find any example of this in the code. 

thanks in advance!

**Comment by vnermolaev** [comment]
thanks for the clarification. This was my deduction but wanted to have a confirmation.
Sadly, my exposure to Rust is insufficient to take upon such a task.

**Comment by ramrengaswamy** [comment]
Took a first pass at this.
Let me know if the approach in my PR makes sense and I can add the necessary unit tests.
So far, I have tested these changes against a Confluent Cloud hosted stream.

**Comment by aierui** [comment]
@crepererum  ping.

**Comment by crepererum** [comment]
@aierui There is an open PR (#129) which seem to have stalled. If you (or somebody else) wanna pick it up, feel free to do so.

**Comment by crepererum** [comment]
SASL PLAIN is now supported, see #216.

**Comment by Neustradamus** [comment]
Good job!

Linked to:
- https://github.com/scram-sasl/info/issues/1
- @ramrengaswamy: https://github.com/influxdata/rskafka/pull/129
- @seijik42: https://github.com/influxdata/rskafka/pull/198
- @toondaey: https://github.com/influxdata/rskafka/pull/216
