### ISSUE TITLE
Could async be removed from these functions?

### ISSUE THREAD

**Issue by segeljakt** [influxdata/rskafka#133]
There are functions that do not contain async code. Currently, I need to use `futures::executor::block_on` to execute these two functions.
* https://github.com/influxdata/rskafka/blob/bd61405d1258791ef9eec43ab47c76256b2cd6d8/src/client/mod.rs#L113-L115
* https://github.com/influxdata/rskafka/blob/bd61405d1258791ef9eec43ab47c76256b2cd6d8/src/client/controller.rs#L30-L37
* https://github.com/influxdata/rskafka/blob/bd61405d1258791ef9eec43ab47c76256b2cd6d8/src/client/mod.rs#L118-L128

Could async be removed for these two or is there a reason it is used?

**Comment by crepererum** [comment]
I think the reasons where that someone thought that calling functions might involve some IO in the future, but that's currently not the case. I therefore think we can just make them sync for now.
