### ISSUE TITLE
Derive `Clone` for `Client`

### ISSUE THREAD

**Issue by segeljakt** [influxdata/rskafka#134]
Clients are not cloneable at the moment:

https://github.com/influxdata/rskafka/blob/bd61405d1258791ef9eec43ab47c76256b2cd6d8/src/client/mod.rs#L106-L109

Would it be an OK addition to derive `Clone`? Right now I need to wrap the client in another `Arc`.

**Comment by crepererum** [comment]
From an API perspective I would like to avoid that, since there is no intuitive description for "cloning a client". What are you cloning? The client connection config, the connections themselves, the pool reference (which would happen if you just derive Clone)?

**Comment by segeljakt** [comment]
I wanted to be able to keep a reference to the client in multiple places and saw there was only an Arc inside the Client, so cloning would be enough to achieve it. It's ok though, and I think what you say makes sense so I will probably stick to `Arc<Client>`.
