### ISSUE TITLE
i dont want import time::OffsetDateTime

### ISSUE THREAD

**Issue by joshua86z** [influxdata/rskafka#144]
```
let record = Record {
            key: None,
            value: Some(b"hello kafka".to_vec()),
            headers: BTreeMap::from([]),
            timestamp: OffsetDateTime::now_utc(),
        };
```
i am already import `chrono`
i dont want import `time`
😃

**Comment by crepererum** [comment]
1. We re-export `time` for you, so you don't need to add it to your direct dependencies. Just `use rskafka::time;`.
2. You can convert between `time` and `chrono` types manually (e.g. by using unix timestamps)
3. Supporting multiple time libraries is out of range for this crate. Should the overwhelming majority of rust community swing back from `time` to `chrono` (after doing the opposite half a year ago while `chrono` was basically abandoned), we may reconsider our choice.
