### ISSUE TITLE
Should there be a maximum retry/backoff amount?

### ISSUE THREAD

**Issue by carols10cents** [influxdata/rskafka#65]
It looks to me that everywhere there's a `loop` that uses `Backoff` such as [in `request_metadata`](https://github.com/influxdata/rskafka/blob/377b1c104fa05bec5a45b92ddea3815cd507c8b8/src/connection.rs#L104-L145), the `loop` could continue forever if it continues to get non-fatal errors. 

Should it? I would expect operations to eventually time out, but that's my general expectation, I'm not sure what Kafka clients are expected to do.

I see that `Backoff` has a `max_backoff` duration, but that seems to be the maximum time any one retry will wait, not the total time to continue retrying.

In the [librdkafka configuration properties list](https://github.com/edenhill/librdkafka/blob/2b76b65212e5efda213961d5f84e565038036270/CONFIGURATION.md), I see settings like  `socket.timeout.ms` and `message.timeout.ms` that sound like they might be overall timeouts in various situations but I'm not very confident I'm understanding that right...

**Comment by crepererum** [comment]
This was fixed in #215.
